---

ansible_connection: winrm
ansible_port: 5985
ansible_winrm_scheme: http
ansible_winrm_transport: kerberos
ansible_winrm_kinit_mode: auto
ansible_winrm_kerberos_delegation: true
ansible_winrm_server_cert_validation: ignore
ansible_winrm_realm: GMTI.GBAHN.NET

