--- # Tasks for spacewalk registration
# ansible_distribution
# ansible_distribution_major_version

- name: Install Spacewalk Client Repo
  yum:
      name: "{{ spw_client_repo }}"
      state: present

- name: install Spacewalk prerequisites
  yum: 
    name: "{{ item }}"
    state: present
  with_items: "{{ spw_packages }}"

- name: deploy configurations
  template: 
    src: "{{ item }}"
    dest: /etc/sysconfig/rhn/{{ item }}
  with_items:
    - up2date
    - rhnsd
  tags:
    - config

- name: Check for Spacewalk server SSL certificate
  stat: 
    path: "{{ spw_cert_file }}"
  register: ssl_file

- name: Fetch and install Spacewalk ORG Trusted SSL Certificate
  get_url:
    url: "{{ spw_cert_uri }}"
    dest: "{{ spw_cert_file }}"
    owner: root
    group: root
    mode: 0644
  when: ssl_file.stat.exists == false

- name: Check for existing registration
  command: /usr/sbin/rhn_check
  register: spw_registered
  ignore_errors: true
  changed_when: false

- name: Import Spacewalk GPG key
  rpm_key:
    key: "{{ spw_gpg_key }}"
    state: present

- name: Register with Spacewalk
  rhn_register:
    server_url: "{{ spw_uri }}"
    sslcacert: "{{ spw_cert_file }}"
    activationkey: "{{ spw_activation_key }}"
    channels: "{{ spw_channels }}"
    state: present
  when: spw_registered|failed

- name: Enable rhnsd service
  service:
    name: rhnsd
    enabled: true
    state: started

- name: Remove packages, post-registration
  yum:
    name: "{{ item }}"
    state: removed
  with_items: "{{ spw_post_reg_remove }}"

- name: Install RHN packages from Spacewalk
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ spw_post_reg_install }}"

- name: Enable RHN Actions Control
  command: rhn-actions-control --enable-all --force
  tags:
    - config
    - allow_actions

