---
- hosts: "{{ group }}"
  gather_facts: no
  connection: ssh
  serial: 20
  vars:
    extra_tests: yes
    install_sudo: no
    ansible_user: root
    authorized_keys_spacewalk: yes
  roles:
      - ansible-client
