# Static Inentory
#
#   - Top level entries are assumed to be groups, start with 'all' to have a full hierchy
#   - Hosts must be specified in a group's hosts:
#     and they must be a key (: terminated)
#   - groups can have children, hosts and vars keys
#   - Anything defined under a hosts is assumed to be a var
#   - You can enter hostnames or ip addresses
#   - A hostname/ip can be a member of multiple groups
#
# Example - 
# all:
#   vars:
#     # Global variables
#   children:
#     atypon_application:
#       vars:
#         # Scoped vars for all atypon_application
#       children:
#         production:
#           vars:
#             # production variables
#           children:
#             web_group1:
#               hosts:
#                 moc-lx000100[01:04].gmti.gbahn.net:
#                 phx-lx000101[01:04].gmti.gbahn.net:
#             db_group1:
#               hosts:
#                 moc-wn00011001.gmti.gbahn.net:
#                 phx-wn00011101.gmti.gbahn.net:

all:
  vars:
    sacewalk_host: moc-lx00011361.gmti.gbahn.net
    loghost: loghost
    ntp_servers: ['time1','time2']
  children:
    infrastructure:
      hosts:
        moc-lx00011361.gmti.gbahn.net:

