--- # Run package module to upgrade all packages on linux systems.

- hosts: "{{ group | default('linux') }}"
  ansible_connection: ssh
  ansible_user: ansible
  ansible_become: yes
  ansible_become_method: sudo
  gather_facts: no

  tasks:
    - name: upgrade all packages
      package:
          name: '*'
          state: latest
      register: package_result
    - debug: var=package_result
  

