---
- hosts: "{{ group }}"
  become: no
  gather_facts: yes

  tasks:

    - name: Remove the Registration PSK File on Windows
      when: ansible_os_family == "Windows"
      block:
        - name: Set the TW config path
          set_fact:
            tw_config_dir: "{{ ansible_env.ProgramData }}\\Tripwire\\agent\\config"

        - name: Remove the Registration PSK File
          win_file:
            path: "{{ tw_config_dir }}\\registration_pre_shared_key.txt"
            state: absent

    - name: Reove the Registration PSK File on Linux
      when: ansible_os_family != "Windows"
      block:
        - name: Registration PSK File
          file:
            path: /etc/tripwire/registration_pre_shared_key.txt
            state: absent


# vi: ft=ansible
