---
#This playbook will install windows updates of all the categories on the machines for the group mentioned as the argument and reboot the server
#The following command should be run to install the updates
# ansible-playbook update-windows-all-patches.yml --extra-vars "hosts=inventory_group_name"
- hosts: '{{ hosts }}' 
  gather_facts: yes 
  vars:
     contents: "{{ lookup('file', '/home/ansible/playbooks/windows/facts/ansible_wu.txt') }}"
  tasks:
    - name: Find out the windows updates (all) that machine needs. 
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: searched 
        log_path: c:\ansible_wui_list.txt 
      register: found_update_count 
         
    - name: Display (all) updates. 
      debug: var=found_update_count
      tags: Updates
    
    - name: Make a decision if you want  to continue with windows patches being install on the machines. 
      pause: prompt='Please confirm you want to continue! Press return to continue. Press Ctrl+c and then "a" to abort'

    - name: Install (all) the updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: installed
        log_path: c:\ansible_wui_installed.txt
      register: check_finish 

    - name: Check on reboot requirement. 
      debug: var=check_finish  

    - name: Reboot if needed.
      win_reboot:
        pre_reboot_delay_sec: 10
      when: check_finish.reboot_required != false

