#The following command should be run to install the updates

# ansible-playbook win-critsec.yml --ask-vault-pass --extra-vars "group=<group_name>"

- hosts: '{{ group }}'
  gather_facts: yes
  tasks:
    - name: Verify the Windows Update Service is running
      win_service:
        name: wuauserv
        state: started
      register: service_info

    - name: Find all Critical and Security updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      tags: find_updates

    - name: Display (all) updates.
      debug: 
        msg: "{{ inventory_hostname }} has {{ found_updates.found_update_count }} updates available."
      when: found_updates.found_update_count > 0

    - name: Slack Ansible Channel Upates Applied
      slack:
        token: "{{ slack_token }}"
        channel: #ansible
        username: "Enterprise-Ansible"
        icon_url: "{{ slack_icon_url }}"
        msg: "NOTICE: {{ inventory_hostname }} has {{ found_updates.found_update_count }} to be applied."
        color: warning
      delegate_to: localhost
      when: found_updates.found_update_count > 0

