#The following command should be run to install the updates

# ansible-playbook win-critsec.yml --ask-vault-pass --extra-vars "group=<group_name>"

- hosts: '{{ group }}'
  gather_facts: yes
  tasks:
    - name: Verify the Windows Update Service is running
      win_service:
        name: wuauserv
        state: started
      register: service_info

    - name: Find all Critical and Security updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      notify: "Slack_Updates_Fond"
      tags: find_updates

    - name: Display (all) updates.
      debug: var=found_updates

  handlers:
    - name: Slack Ansible Channel Upates Found
      listen: "Slack_Updates_Fond"
      slack:
        token: "{{ slack_token }}"
        channel: #ansible
        username: "Enterprise-Ansible"
        icon_url: "{{ slack_icon_url }}"
        msg: "NOTICE: Updates have been found for: {{ inventory_hostname }}"
        color: warning
      delegate_to: localhost

