#The following command should be run to install the updates

# ansible-playbook win-critsec.yml --ask-vault-pass --extra-vars "group=<group_name>"

- hosts: '{{ group }}'
  gather_facts: yes
  tasks:
    - name: Find all Critical and Security updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      notify: Slack Maintenance Channel Updates Available
      tags: find_updates

    - name: Display (all) updates.
      debug: var=found_updates

  handlers:
    - name: Slack Maintenance Channel Updates Available
      slack:
        token: "{{ slack_token_maint }}"
        icon_url: "{{ slack_icon_url }}"
        username: "Ansible"
        color: good
        msg: "NOTICE: {{ inventory_hostname }} has updates available. (not applied)"
      delegate_to: localhost

