--- # This playbook will install windows updates of Security and Critical categories

#The following command should be run to install the updates

# ansible-playbook win-update-critsec.yml --ask-vault-pass --extra-vars "group=<group_name>"

- hosts: '{{ group }}'
  gather_facts: yes
  serial: 200
  tasks:

  - name: Set Facts
      set_fact:
        cntr_user: "{{ lookup('env','USER') }}"
        cntr_hostname: "{{ lookup('env','HOSTNAME') }}"

    - name: Report host list to Slack
      slack:
        token: "{{ slack_token }}"
        channel: #ansible
        domain: "gannettdigital.slack.com"
        username: "Enterprise-Ansible"
        icon_url: "{{ slack_icon_url }}"
        msg: "Playbook:   win-update-critsec.yml\nHost Group: {{ group }}\nFrom Host:  {{ cntr_hostname }}\nBy User:    {{ cntr_user }}\nRunning as: {{ ansible_user_id }}\n--------------\n{{ ansible_play_batch | join('\n') }}"
        color: good
      delegate_to: localhost
      run_once: true

    - name: Verify the Windows Update Service is running
      win_service:
        name: wuauserv
        state: started
      register: service_info

    - name: Find all Critical and Security updates.
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      tags: find_updates

    - name: Display available updates.
      debug:
        msg: "{{ inventory_hostname }} has {{ found_updates.found_update_count }} updates available."

    - name: Make a decision if you want  to continue with windows patches being install on the machines.
      pause:
          prompt: "Do you want to install and reboot, if needed? Enter 'Y' to continue."
      register: result

    - name: Exit if anything other than Y
