--- # Access and notification test for Windows Systems

- hosts: '{{ group | default("windows") }}'
  gather_facts: yes
  tasks:
    - name: Set Facts
      set_fact:
        cntr_user: "{{ lookup('env','USER') }}"
        cntr_hostname: "{{ lookup('env','HOSTNAME') }}"

    - name: Report host list to Slack
      slack:
        token: "{{ slack_token }}"
        channel: #ansible
        domain: "gannettdigital.slack.com"
        username: "Enterprise-Ansible"
        icon_url: "{{ slack_icon_url }}"
        msg: "Playbook:   win-update-critsec.yml\nHost Group: {{ group }}\nFrom Host:  {{ cntr_hostname }}\nBy User:    {{             cntr_user      }}\nRunning as: {{ ansible_user_id }}\n--------------\n{{ansible_play_batch|join('\n') }}"
        color: good
      delegate_to: localhost
      run_once: true

    - name: Report host list via Email
      mail:
        host: smtp
        port: 25
        subject: "Ansible Play Report for Group: {{ group | default('windows') }}"
        to: dmaple@gannett.com
        from: ansible@moc-lx00011359.gmti.gbahn.net
        body: "Group: {{ group | default('windows') }}\n--------------\n{{ansible_play_batch|join('\n') }}"
      delegate_to: localhost
      run_once: true

    - name: run ipconfig
      raw: ipconfig
      register: ipconfig
      changed_when: true
    - debug: var=ipconfig

    - name: test stat module on file
      win_stat: path="C:/Windows/win.ini"
      register: stat_file
    - debug: var=stat_file

    - name: check stat_file result
      assert:
        that:
          - "stat_file.stat.exists"
          - "not stat_file.stat.isdir"
          - "stat_file.stat.size > 0"
          - "stat_file.stat.md5"

    - name: Verify the Windows Update Service is running
      win_service:
          name: wuauserv
          state: started
          register: service_info

# vi: ft=ansible
