--- # This playbook will install windows updates of all the categories on the machines for the group mentioned as the argument and reboot the server
#The following command should be run to install the updates
# ansible-playbook win-update-all.yml --ask-vault-pass --extra-vars "group=[group_name | hostname]"

- hosts: '{{ group }}'
  gather_facts: no
  tasks:

    - name: Report host list to Slack
      slack:
        token: "{{ slack_token }}"
        channel: #ansible
        domain: "gannettdigital.slack.com"
        username: "Enterprise-Ansible"
        icon_url: "{{ slack_icon_url }}"
        msg: "Ansible Playbook: win-update-critsec.yml\nGroup: {{ group }}\n--------------\n{{ansible_play_batch|join('\n') }}"
        color: good
      delegate_to: localhost
      run_once: true

    - name: Find all avaiable updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: searched
        log_path: c:\ansible_wui_list.txt
      register: found_updates
      tags: find_updates

    - name: Display (all) updates.
      debug: var=found_update

    - name: Prompt for confirmation to install updates.
      pause:
        prompt: "Please confirm update installation and reboot, if needed! Enter 'Y' to continue."
      register: result
    - name: Exit if anything other than Y
      meta: end_play
      when: result.user_input != "Y"

    - name: Install (all) the updates.
      win_updates:
        category_names:
          - Application
          - Connectors
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - ServicePacks
          - Tools
          - UpdateRollups
          - CriticalUpdates
          - SecurityUpdates
          - Updates
          - UpdateRollups
        state: installed
        log_path: c:\ansible_wui_installed.txt
      register: check_finish
      tags: installed_updates

    - name: Reboot if needed.
      win_reboot:
        pre_reboot_delay_sec: 10
      when: check_finish.reboot_required != false
      tags: reboot


