--- # Axon Agent install tasks for Linux

- name: Set package architecture for RedHat x86_64
  set_fact:
    windows_agent_msi: "{{ repository_server }}/{{ windows_x64_agent }}"
    platform_family: "Windows"
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture == "64-bit"

- name: Set package architecture for Windows i386
  set_fact:
    windows_agent_msi: "{{ repository_server }}/{{ windows_x86_agent }}"
    platform_family: "Windows"
  when:
    - ansible_os_family == "Windows"
    - ansible_architecture != "64-bit"

- name: Set Program Data Directory
  set_fact:
    tw_config_dir: "{{ ansible_env.ProgramData }}\\Tripwire\\agent\\config"

- name: Create the tripwire config directory
  tags: config
  win_file:
    path: "{{ tw_config_dir }}"
    state: directory

- name: Install the twagent config template
  tags: config
  win_template:
    src: twagent.conf.j2
    dest: "{{ tw_config_dir }}\\twagent.conf"
  register: twconfig_result

- name: Install the temporary PSK file
  tags: config
  win_copy:
    src: registration_pre_shared_key.txt
    dest: "{{ tw_config_dir }}\\registration_pre_shared_key.txt"
  when: twconfig_result.changed == True

- name: Install the metadata.yml tag file
  win_template:
    src: metadata.yml.j2
    dest: "{{ tw_config_dir }}\\metadata.yml"

- name: Install the MSI from the web server
  win_package:
    path: "{{ windows_agent_msi }}"
    creates_path: C:\Program Files\Tripwire\Agent\twagent.exe
    creates_service: TripwireAxonAgent
    validate_certs: no
  register: package_result

- name: Debug from package_result
  debug:
    var: package_result

# vi: ft=ansible
