--- # Axon Agent install tasks for Linux

- name: Set package architecture for 64-bit Linux
  set_fact:
    linux_agent_rpm: "{{ repository_server }}/{{ linux_x64_agent_rpm }}"
    linux_egdrv_rpm: "{{ repository_server }}/{{ linux_dkm_egdrv_rpm }}"
    linux_egsvc_rpm: "{{ repository_server }}/{{ linux_x64_egsvc_rpm }}"
    platform_family: "Red Hat"
  when:
    - ansible_os_family == "RedHat"
    - ansible_architecture == "x86_64"

- name: Set package architecture for 32-bit Linux
  set_fact:
    linux_agent_rpm: "{{ repository_server }}/{{ linux_i386_agent_rpm }}"
    linux_egdrv_rpm: "{{ repository_server }}/{{ linux_dkm_egdrv_rpm }}"
    linux_egsvc_rpm: "{{ repository_server }}/{{ linux_i386_agent_rpm }}"
    platform_family: "Red Hat"
  when:
    - ansible_os_family == "RedHat"
    - ansible_architecture == "i386"

- name: Create /etc/tripwire directory
  tags: config
  file:
    path: /etc/tripwire
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install the twagent config template
  tags: config
  template:
    src: twagent.conf.j2
    dest: /etc/tripwire/twagent.conf
    owner: root
    group: root
    mode: 0644
  register: twconfig_result

- name: Install the temporary PSK file
  tags: config
  lineinfile:
    path: /etc/tripwire/registration_pre_shared_key.txt
    line: "{{ registration_psk }}"
    create: yes
    insertbefore: BOF
    owner: root
    group: root
    mode: 0644
  when: twconfig_result.changed == True

- name: Install the metadata.yml tag file
  template:
    src: metadata.yml.j2
    dest: /etc/tripwire/metadata.yml
    owner: root
    group: root
    mode: 0644

- name: Install DKMS prerequisites
  tags: yum,dkms,install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - dkms
    - kernel-headers
    - kernel-devel
  register: prereq_install

- name: Check if running kernel matches latest installed kernel
  tags: kernel_test
  shell: if [ "`rpm -q kernel --qf '%{installtime} %{version}-%{release}.%{arch}\n'|sort -n -k1|tail -1|cut -d ' ' -f 2`" =        "`uname -r`"  ]; then echo "running latest installed kernel."; else echo "needs to be rebooted."; fi
  ignore_errors: true
  changed_when: false
  register: reboot_test

- name: Output result of kernel update check
  tags: kernel_test
  debug:
    msg: "{{ inventory_host }} {{ reboot_test.stdout }}"

- name: Install the Axon Agent Event Generator Driver
  tags: yum,eg,install
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
    validate_certs: no
  with_items:
    - "{{ linux_agent_rpm }}"
    - "{{ linux_egdrv_rpm }}"
    - "{{ linux_egsvc_rpm }}"
  register: agent_install

- name: Start the tw-eg-service service
  tags: service
  service:
    name: tw-eg-service
    state: started
    enabled: yes

- name: Start the tripwire-axon-agent service
  tags: service
  service:
    name: tripwire-axon-agent
    state: started
    enabled: yes

# vi: ft=ansible
