--- # Tasks for setting up a linux system as an Ansible client

- name: Check/install ansible group with GID = 4242
  tags: ansible-group
  group:
      name: ansible
      gid: 4242
      state: present

- name: Check for ansible user with UID = 4242
  tags: ansible-user
  user:
      name: ansible
      uid: 4242
      comment: "Ansible User"
      group: ansible
      home: /home/ansible
      createhome: yes
      update_password: always
      password: "{{ ansible_encrypted_password }}"
- name: Add Authorized Keys
  tags: ansible-keys
  authorized_key:
      user: ansible
      state: present
      manage_dir: yes
      exclusive: yes
      key: "{{ lookup('file', '../files/authorized_keys') }}"
- name: Install sudo (RedHat-like)
  tags: sudo-package
  yum: 
      name: sudo
      state: present
- name: Create sudoers.d directory
  tags: sudoers.d-directory
  file:
      path: /etc/sudoers.d
      owner: root
      group: root
      mode: 0755
      state: directory
- name: Set includedir in sudoers
  tags: sudoers-include
  lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"
- name: Create sudoers file
  tags: sudoers-file
  template:
      src: sudoers.d.j2
      dest: "/etc/sudoers.d/{{ sudoers_filename }}"
      mode: 0440
      owner: root
      group: root
      validate: "/usr/sbin/visudo -cf %s"

